name: "Deploy"
on: 
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Set up Ruby 2.4.1 and perform bundle install.
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4.1

      - name: Install bundler specific version
        run: gem install bundler:1.15

      - name: Install dependencies
        run: bundler _1.15_ install  

      - name: Update apt-get.
        run: sudo apt-get update

      - name: Install pngquant.
        run: sudo apt-get install -y pngquant
      
      - name: Install jpegoptim.
        run: sudo apt-get install -y jpegoptim

      - name: Optimize images and generate static site.
        run: ./scripts/cibuild.sh
        